version: "3.9"

services:

    # Build scheduler to update s3
    scheduler:
        image: mdvaccinewatch-scheduler:latest
        container_name: mdvaccinewatch_scheduler_container
        build: ./scheduler
        env_file: .env

    # Build frantend webapp
    web:
        image: mdvaccinewatch-web:latest
        container_name: mdvaccinewatch_web_container
        build: ./app
        env_file: .env
        ports:
        - 8080:8080
